### ISSUE TITLE
CSS Inheritence

### ISSUE THREAD

**Issue by cyouh95** [bartbaetens/prj-rev-bwfs-dasmoto#2]
Alternatively, you could specify `font-family: "Helvetica"` for the `body` element. That way, all its children elements would automatically inherit this property without you needing to specify it for each element.

```css
body {
  font-family: "Helvetica";
}
```
